### PR TITLE
modify sanity check script parameters, script name

### PR DESCRIPTION
**Pull request by lfunderburk**
Added new variables - there is a lot more variables than before. 

Ideally a user would verify the data as 
scripts/verify_metadata http://localhost/airr/v1/repertoire my-ireceptor-metadatafile.csv /data 

That might require me to add extra machinery (array files, or other mechanism to read corresponding data), it will also require that I have a fixed mapping file I use in the test, and that there is some mechanism that creates JSON input files for the queries to complete the test.

### CODE REVIEW

**Comment by lfunderburk** [comment]
Modified wrapper script for repertoire tests  https://github.com/sfu-ireceptor/turnkey-service-php/blob/update-repertoire-sanity-check/scripts/verify_dataload.sh

Latest sanity checking scripts and documentation here
https://github.com/sfu-ireceptor/dataloading-mongo/tree/master/verify 

Need help review before merging - in particular, feedback on whether each time I run a new python script, I need to call ` sudo -E docker-compose`

Also noticed that after running this command, common bash commands and comment are coloured differently. 

Can I call bash commands in between two separate docker commands?

**Comment by lfunderburk** [comment]
Note to self 
Mappping file should be in the Docker container in /app/config/

**Comment by lfunderburk** [comment]
sh: 1: /app/verify/joint_sanity_testing.sh: Permission denied
sh: 5: /app/verify/nofilters.json: Permission denied
 Getting the errors above. 
@jeromejaglale  how can I give my script reading and executing permissions in Docker environment setup to run scripts?

**Comment by lfunderburk** [comment]
Also, I added a few echo commands in this script and noticed that in previous iterations of testing, the echo messages were not appearing when running from scripts folder. 
Currently using dummy data to test
`scripts/verify_dataload.sh "http://localhost/airr/v1/repertoire" test_data/PRJNA330606_Wang_1_sample_metadata.csv /home/lgfunderburk/Documents/OUTPUT_ANNO_DIR PRJNA330606`

Echo commands and latest script here https://github.com/sfu-ireceptor/dataloading-mongo/blob/master/verify/joint_sanity_testing.sh 

How can I ensure that the latest code in master branch is what is being used from Turnkey @jeromejaglale ?

**Comment by lfunderburk** [comment]
Tested script on 
`scripts/verify_dataload.sh "http://covid19-1.ireceptor.org/" "test_data/PRJNA628125_Nielsen_Yang_2020-06-10.csv" "/home/lgfunderburk/Documents/OUTPUT_ANNO_DIR/" "PRJNA628125" `

Script runs smoothly :) 

Currently testing what happens when the researcher provides different kinds of servers as input.

**Review by bcorrie — APPROVED** [review]
This looks ready to me...

**Comment by bcorrie** [comment]
@jeromejaglale can you have a look at this. No impacts on other scripts so isolated changes only. One thing to check and get feedback on. The docker compose mounts two directories to the container that the script uses for input and output. This is similar to the other scripts except their mounts are done through docker compose - which didn't provide the flexibility that we needed. Can you review verify_dataload.sh.

**Comment by jeromejaglale** [comment]
The Docker containers are on the same virtual network. Their names are defined in `docker-compose.yml`. From any container, to query the API container, this works:

`curl --data "{}" "http://ireceptor-api/airr/v1/repertoire"`

So, I think `ireceptor-api` can be hardcoded in `verify_dataload.sh` so the user doesn't have to pass that parameter?

**Comment by jeromejaglale** [comment]
In README, about `scripts/verify_dataload.sh http://xx.xx.xx.xx/ PRJNA330606 test_data PRJNA330606_Wang_1_sample_metadata.csv /tmp`:

It might be good to briefly explain, right there, what are the parameters `PRJNA330606` and `/tmp`?  By adding them to a sentence like this, for example: this will verify that the data returned by the web service matches the repertoire metadata in `PRJNA330606_Wang_1_sample_metadata` and the rearrangements files in `test_data`.

If there are errors, it would be good to clearly state what is the next step for the user? Contact us? Look into the log files? Read a specific section of sanitychecking.md? (link to it?)

**Comment by bcorrie** [comment]
Both changes made and tested...

**Pull request merged**
