### PR TITLE
Updated Docker Compose syntax

### PR DESCRIPTION
**Pull request by alxcost**
Hello folks,

Docker Compose has been updating their syntax to deprecate the old `docker-compose` binary. Now it should be `docker compose` without the dash. 
In addition, the `--file` flag seems to have been dropped in the new Docker Compose and it's now simply `-f`.

More details at: https://docs.docker.com/compose/migrate/

It's a small change but the old `docker-compose` no longer works on some newer operating systems. 
On our end it seems `docker-compose` no longer works even on Ubuntu 22.04 LTS, thus we needed to update the scripts to the newer syntax.

### CODE REVIEW

**Comment by alxcost** [comment]
Actually I just realized the install script uses a very specific (although old) version of docker compose here: https://github.com/sfu-ireceptor/turnkey-service-php/blob/ea2ae39ac4eebb19b9c1bd6861c7f44c0cded357/scripts/install_turnkey.sh#L24

The steps for installing the newer docker compose manually also changed, and it should no longer be placed on `/usr/local/bin/`  but rather on Docker's `cli-plugins`:
https://github.com/docker/compose?tab=readme-ov-file#where-to-get-docker-compose

**Comment by bcorrie** [comment]
Hi @alxcost thanks for the patch. 

Yes, I was just going to point that out. We are running new OSes (e.g. Ubuntu 24.04 LTS) which are working fine. You probably are running on a VM that doesn't have the Turnkey specific docker installed but rather a newer version...

I will have to think about how to support our current installations as well as using the newer docker compose. I need to investigate whether those commands are backwards compatible.

I might suggest that I create a production-v4-docker-update branch, and then have you do a pull request to merge into that branch. We can then use that as the production-v4 branch that uses a newer docker (and docker compose) release.

**Comment by bcorrie** [comment]
@alxcost I have created a `docker-update` branch, can you make the pull request against that rather than production-v4

**Comment by alxcost** [comment]
Hi Brian,

Thank you, I'll do that! In hindsight doing a pull request against a production branch might not have been a good idea.

**Pull request closed without merging**
